<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer: The visible input to the model. Can be called the feature or variable type. 3 columns in the training set would mean 3 input layers. 
### Hidden Layer: The layer where all adjustments are made to the initial inputs in order to output to the output layer.  
### Output Layer: The visible output layer e.g. prediction. 
### Neuron: A specialized cell in the human body responsible for sending electrical information to and from parts of the human body. The signal transferance mechanism. In terms of 
#### NN, it is the mechanism within the hidden layer that performs the activation function before it gets send to the output layer.   
### Weight: The adjustment to each record of an input (feature) prior to its transformation in the hidden layer. It is a coefficient that gets adjusted prior to each subsequent activation.   
### Activation Function: Functions that modify the data they recieve prior to passing it to the next layer. 
### Node Map: Visual diagram of the layer differentiation and layer connections to each node in a Neural Network. 
### Perceptron: Single layer in a Neural Network.


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### The signal flow of a neural network starts with the inputs e.g. features of our model. On the very first trip to the hidden layer, these inputs do not get weights applied to them vs. subsequent trips between hidden layers prior to going to the output. The next phase includes the Neuron, or the mechanism involved in applying the activation function to the inputs. Each Neuron recieves one data point from every feature and then applies the activation function and a bias (update to the Y intercept), which can be considered an attempt at a prediction. Once applied, the Neuron's output values are combined with all other values of all other Neuron's in the hidden layer and scored. Depending on the score, either a subsequent hidden layer succesfully increases the score or it remains static. The objective is to determine the amount of hidden layers required to increase the accuracy of our prediction model.   

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [45]:
import numpy as np
import pandas as pd
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

inputs = df[["x1","x2"]]
correct_outputs = df[["y"]]

In [99]:
def perceptron_nand_gate():
    weights = np.ones(len(df.columns))
    bias = 0 - (len(df.columns) - 1)
    weighted_sum = np.dot(df, weights) + bias
    
    def activate(x):
        return np.piecewise(x, [x <= 0, x > 0], [1,0])
    return activate(weighted_sum)

In [100]:
perceptron_nand_gate()

array([1., 1., 1., 1.])

In [94]:
weights = np.ones(len(df.columns))
weights

array([1., 1., 1.])

In [95]:
bias = 0 - (len(df.columns) - 1)
bias

-2

In [96]:
weighted_sum = np.dot(df,weights) + bias
weighted_sum

array([-1.,  0.,  0.,  0.])

In [86]:
df

x1  x2  y
0   0   0  1
1   1   0  1
2   0   1  1
3   1   1  0

In [97]:
# activated_output = np.piecewise(weighted_sum, [weighted_sum <= 0, weighted_sum > 0], [1,0])
activated_output = 
activated_output

array([1., 1., 1., 1.])

## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [102]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [127]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]
X = diabetes[feats]
scaler = MinMaxScaler()
scaler.fit(X)
X = scaler.transform(X)
y = diabetes["Outcome"]

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/preprocessing/data.py:323: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


In [129]:
len(y)

768

In [136]:
len(X[0])

8

In [139]:
len((np.random.random(len(X[0])) - 1)[1:])

7

In [165]:
##### Update this Class #####

class Perceptron(object):
    
    def __init__(self, rate = 0.01, niter = 10):
        self.niter = niter
    
    def __sigmoid(self, x):
        return (1 / (1 + np.exp(-x)))
    
    def __sigmoid_derivative(self, x):
        sx = sigmoid(x)
        return sx * (1-sx)

    def fit(self, X, y):
        """Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """
        # Randomly Initialize Weights
        self.weight = np.random.random(len(X[0])) - 1 

        for i in range(self.niter):
            err = 0
            for xi, target in zip(X, y):
                delta_w = self.rate * (target - self.predict(xi))
                # Update the Weights
                self.weight[1:] += delta_w * xi
                self.weight[0] += delta_w
                err += int(delta_w != 0.0)
            self.errors.append(err)
        return self

            # Weighted sum of inputs / weights

            # Activate!

            # Cac error

    def predict(self, X):
        """Return class label after unit step"""
        return np.where(self.net_input(X) >= 0.0, 1, -1)

In [166]:
Perceptron(10)

In [167]:
p = Perceptron(10)

In [168]:
p.fit(X,y)

AttributeError: 'Perceptron' object has no attribute 'rate'

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?

In [142]:
a = np.arange(10)

In [146]:
np.where(a < 5, a, 0)

array([0, 1, 2, 3, 4, 0, 0, 0, 0, 0])