<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>

# Backpropagation Practice

## *Data Science Unit 4 Sprint 2 Assignment 2*

Implement a 3 input, 4 node hidden-layer, 1 output node Multilayer Perceptron on the following dataset:

| x1 | x2 | x3 | y |
|----|----|----|---|
| 0  | 0  | 1  | 0 |
| 0  | 1  | 1  | 1 |
| 1  | 0  | 1  | 1 |
| 0  | 1  | 0  | 1 |
| 1  | 0  | 0  | 1 |
| 1  | 1  | 1  | 0 |
| 0  | 0  | 0  | 0 |

If you look at the data you'll notice that the first two columns behave like an XOR gate while the last column is mostly just noise. Remember that creating an XOR gate was what the perceptron was criticized for not being able to learn. 

In [7]:
import numpy as np
import pandas as pd
data = { 'x1': [0,0,1,0,1,1,0],
         'x2': [0,1,0,1,0,1,0],
         'x3': [1,1,1,0,0,1,0],
         'y':  [0,1,1,1,1,0,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

inputs = df[["x1","x2","x3"]]
correct_output = df[["y"]]

In [8]:
weighted_sum = perceptron_nand_gate()
weighted_sum

array([[ 0],
       [-1],
       [-1],
       [ 0],
       [ 0],
       [-2],
       [ 1]])

In [38]:
class simplePerceptron:
    def __init__(self):
        self.inputs = 3
        self.hidden = 4 
        self.output = 1
        
        self.weights = np.random.rand(self.inputs, self.hidden)
        # weights in shape of 3 x 4 
        self.weights2 = np.random.rand(self.hidden, self.output)
        
    def sigmoid(self, s):
        return 1 / (1 + np.exp(-s))
    
    def sigmoid_derivative(self, s):
        return s * (1 - s)
    
    def feed_forward(self, X):
        """Perform steps 2 - 5"""
        self.first_weighted_sum = np.dot(X, self.weights)
        
        self.activated_hidden = self.sigmoid(self.first_weighted_sum)
        
        self.second_weighted_sum = np.dot(self.activated_hidden, self.weights2)
        
        self.activated_output = self.sigmoid(self.second_weighted_sum)
        
        return self.activated_output
    
    def back_propogate(self, X, y):
        """Backpropogate"""
        # Computing error; difference of actual and predicted 
        self.error_output = y - self.activated_output
        
        self.delta_output = self.error_output * self.sigmoid_derivative(self.activated_output)
        
        self.error_hidden = np.dot(self.delta_output, self.weights2.T)
        
        self.delta_hidden = self.error_hidden * self.sigmoid_derivative(self.activated_hidden)
        
        # Adjustments to weights and weights2
        self.weights += np.dot(X.T, self.delta_hidden)
        self.weights2 += np.dot(self.activated_hidden.T, self.delta_output)
        
        return True 
        
    def train(self, X, y, iter=10000):
        #Always good idea to return something even if you don't have to
        for epoch in range(iter):
            self.feed_forward(X)
            self.back_propogate(X, y)
        return self.__dict__
        
    def predict(self, X):
        return [1 if prediction > 0.5 else 0 for prediction in self.feed_forward(X)]

In [39]:
X = df[["x1","x2","x3"]]
y = df[["y"]].values

In [40]:
perceptron = simplePerceptron()

In [41]:
perceptron.train(X,y)

{'inputs': 3,
 'hidden': 4,
 'output': 1,
 'weights': array([[-3.94876085,  6.89165957, -2.00175882,  5.53523316],
        [ 6.9315279 , -4.15430185, -1.70828415,  5.50818065],
        [ 0.79765283,  1.09331662, -1.51839369,  0.12412393]]),
 'weights2': array([[-9.77068103],
        [-9.87486689],
        [-3.60622245],
        [15.0009424 ]]),
 'first_weighted_sum': array([[ 0.79764787,  1.0933149 , -1.5183748 ,  0.12411786],
        [ 7.72913472, -3.06096788, -3.22659092,  5.63228575],
        [-3.15109257,  7.98493501, -3.52007848,  5.65933815],
        [ 6.93148685, -4.15428278, -1.70821613,  5.50816789],
        [-3.94874044,  6.89162011, -2.00170368,  5.53522029],
        [ 3.78039428,  3.83065223, -5.22829461, 11.16750604],
        [ 0.        ,  0.        ,  0.        ,  0.        ]]),
 'activated_hidden': array([[0.68947111, 0.74900543, 0.17970096, 0.53098969],
        [0.99956037, 0.04474631, 0.03817723, 0.99643239],
        [0.04104825, 0.99965956, 0.0287463 , 0.99652728],
 

In [42]:
perceptron.predict(X)

[0, 1, 1, 1, 1, 0, 0]

# Plotting Learning Curve

In [ ]:
import matplotlib.pyplot as plt
plt.plot(T.J)
plt.xlabel('Iterations')
plt.ylabel('Cost')
plt.show()  

## Try building/training a more complex MLP on a bigger dataset.

Use the [MNIST dataset](http://yann.lecun.com/exdb/mnist/) to build the cannonical handwriting digit recognizer and see what kind of accuracy you can achieve. 

If you need inspiration, the internet is chalk-full of tutorials, but I want you to see how far you can get on your own first. I've linked to the original MNIST dataset above but it will probably be easier to download data through a neural network library. If you reference outside resources make sure you understand every line of code that you're using from other sources, and share with your fellow students helpful resources that you find.


### Parts
1. Gathering & Transforming the Data
2. Making MNIST a Binary Problem
3. Estimating your Neural Network (the part you focus on)

### Gathering the Data 

`keras` has a handy method to pull the mnist dataset for you. You'll notice that each observation is a 28x28 arrary which represents an image. Although most Neural Network frameworks can handle higher dimensional data, that is more overhead than necessary for us. We need to flatten the image to one long row which will be 784 values (28X28). Basically, you will be appending each row to one another to make on really long row. 

In [2]:
# !pip install tensorflow

In [3]:
import numpy as np
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

In [4]:
# input image dimensions
img_rows, img_cols = 28, 28

In [5]:
# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


In [6]:
x_train = x_train.reshape(x_train.shape[0], img_rows * img_cols)
x_test = x_test.reshape(x_test.shape[0], img_rows * img_cols)

# Normalize Our Data
x_train = x_train / 255
x_test = x_test / 255

In [7]:
# Now the data should be in a format you're more familiar with
x_train.shape

(60000, 784)

In [12]:
x_train[:200]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

### Making MNIST a Binary Problem 
MNIST is multiclass classification problem; however we haven't covered all the necessary techniques to handle this yet. You would need to one-hot encode the target, use a different loss metric, and use softmax activations for the last layer. This is all stuff we'll cover later this week, but let us simply the problem for now: Zero or all else.

In [13]:
import numpy as np

y_temp = np.zeros(y_train.shape)
y_temp[np.where(y_train == 0.0)[0]] = 1
y_train = y_temp

y_temp = np.zeros(y_test.shape)
y_temp[np.where(y_test == 0.0)[0]] = 1
y_test = y_temp

In [40]:
# A Nice Binary target for ya to work with
y_train

array([0., 1., 0., ..., 0., 0., 0.])

# Use a subsample to below 7K at first

### Estimating Your `net


In [52]:
import pandas as pd

sample_index = np.random.randint(x_train.shape[0], size=5000)

sample_index

array([ 8507, 18502,  2852, ..., 29921, 40465, 32999])

In [53]:
x_sample = x_train[sample_index]
y_sample = y_train[sample_index]

In [59]:
x_sample_df = pd.DataFrame(data=x_sample)

In [60]:
x_sample_df.head()

0    1    2    3    4    5    6    7    8    9    ...  774  775  776  777  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   

   778  779  780  781  782  783  
0  0.0  0.0  0.0  0.0  0.0  0.0  
1  0.0  0.0  0.0  0.0  0.0  0.0  
2  0.0  0.0  0.0  0.0  0.0  0.0  
3  0.0  0.0  0.0  0.0  0.0  0.0  
4  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 784 columns]

In [54]:
y_sample_df = pd.DataFrame(data=y_sample)

In [55]:
y_sample_df.shape

(5000, 1)

In [58]:
y_sample_df.head()

0
0  0.0
1  0.0
2  0.0
3  0.0
4  0.0

In [65]:
X = x_sample_df.values
y = y_sample_df.values

In [82]:
class simplePerceptron:
    def __init__(self):
        self.inputs = 784
        self.hidden = 100 
        self.output = 1
        
        self.weights = np.random.rand(self.inputs, self.hidden)
        # weights in shape of 784 x 2 
        self.weights2 = np.random.rand(self.hidden, self.output)
        
    def sigmoid(self, s):
        return 1 / (1 + np.exp(-s))
    
    def sigmoid_derivative(self, s):
        return s * (1 - s)
    
    def feed_forward(self, X):
        """Perform steps 2 - 5"""
        self.first_weighted_sum = np.dot(X, self.weights)
        
        self.activated_hidden = self.sigmoid(self.first_weighted_sum)
        
        self.second_weighted_sum = np.dot(self.activated_hidden, self.weights2)
        
        self.activated_output = self.sigmoid(self.second_weighted_sum)
        
        return self.activated_output
    
    def back_propogate(self, X, y):
        """Backpropogate"""
        # Computing error; difference of actual and predicted 
        self.error_output = y - self.activated_output
        
        self.delta_output = self.error_output * self.sigmoid_derivative(self.activated_output)
        
        self.error_hidden = np.dot(self.delta_output, self.weights2.T)
        
        self.delta_hidden = self.error_hidden * self.sigmoid_derivative(self.activated_hidden)
        
        # Adjustments to weights and weights2
        self.weights += np.dot(X.T, self.delta_hidden)
        self.weights2 += np.dot(self.activated_hidden.T, self.delta_output)
        
        return True 
        
    def train(self, X, y, iter=1000):
        #Always good idea to return something even if you don't have to
        for epoch in range(iter):
            self.feed_forward(X)
            self.back_propogate(X, y)
        return self.__dict__
        
    def predict(self, X):
        return [1 if prediction > 0.5 else 0 for prediction in self.feed_forward(X)]

In [83]:
perceptron = simplePerceptron()

In [84]:
perceptron.train(X,y)

{'inputs': 784,
 'hidden': 100,
 'output': 1,
 'weights': array([[0.27197744, 0.70762825, 0.93490673, ..., 0.62933368, 0.58255197,
         0.79761141],
        [0.70282132, 0.77926475, 0.18128999, ..., 0.03108639, 0.65037309,
         0.03925115],
        [0.798739  , 0.70023785, 0.86025032, ..., 0.32003748, 0.98626702,
         0.93096148],
        ...,
        [0.13858711, 0.70363287, 0.37316954, ..., 0.32120851, 0.06850338,
         0.06810358],
        [0.97142378, 0.82981612, 0.77855434, ..., 0.57081569, 0.30742918,
         0.37475161],
        [0.18747148, 0.33935368, 0.92003243, ..., 0.52575283, 0.48612199,
         0.27032697]]),
 'weights2': array([[2.98885210e-01],
        [2.38447185e-01],
        [6.86893559e-01],
        [7.53289767e-01],
        [6.16978070e-01],
        [9.33354363e-01],
        [5.38499628e-01],
        [7.00130014e-01],
        [8.61728785e-01],
        [1.25334800e-01],
        [2.84732884e-01],
        [1.17090273e-01],
        [8.62630735e-01],
  

In [85]:
np.mean(perceptron.error_output)

-0.9046

In [73]:
#first run!

np.mean(perceptron.error_output)

0.0954

## Stretch Goals: 

- Make MNIST a multiclass problem using cross entropy & soft-max
- Implement Cross Validation model evaluation on your MNIST implementation 
- Research different [Gradient Descent Based Optimizers](https://keras.io/optimizers/)
 - [Siraj Raval the evolution of gradient descent](https://www.youtube.com/watch?v=nhqo0u1a6fw)
- Build a housing price estimation model using a neural network. How does its accuracy compare with the regression models that we fit earlier on in class?